name: Android CI

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -x test -x lint

    - name: Archive APK
      uses: actions/upload-artifact@v2
      with:
        name: SCLPA
        path: app/build/outputs/apk/release/app-release.apk

    - name: Archive APK
      uses: actions/upload-artifact@v2
      with:
        name: SCLPA-debug
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Release
      uses: softprops/action-gh-release@v1
      continue-on-error: true
      with:
        files: app/build/outputs/apk/release/app-release.apk